name    'rbjavier-phabricator'
version '0.0.1'
source 'git://github.com/rbjavier/puppet-phabricator'
author 'rbjavier'
license 'Apache 2.0'
summary 'Phabricator installation'
description 'Install Phabricator, its tools and dependencies'
project_page 'https://github.com/rbjavier/puppet-phabricator'
dependency 'puppetlabs/apache', '>= 0.4.0'
dependency 'puppetlabs/mysql', '>= 0.6.1'
dependency 'rbjavier/git', '>= 0.0.1', 'git://github.com/rbjavier/puppet-git.git'
